In [12]:
#even_odd
def even_odd(num):
    if num % 2 == 0:
        return "Even"
    else:
        return "Odd"
num=int(input("Enter a number: "))
result=even_odd(num)
print("The number", num, "is", result)

The number 3 is Odd


In [13]:
#square
def find_square(numb):
    return numb * numb
numb=int(input())
square=find_square(numb)
print("the square of", numb, "is", square)




the square of 3 is 9


In [14]:
#iterate through a list
# #for loop
fruits=["apple","banana","cherry"]
for x in fruits:
    print(x)
#range function
for x in range(6):
    print(x)
#incrementing the range
for x in range(2, 30, 3):
    print(x)
#decrementing the range
for x in range(50,5,5):
    print(x)

apple
banana
cherry
0
1
2
3
4
5
2
5
8
11
14
17
20
23
26
29


In [15]:
#using numpy
import numpy as np
N=np.array([10,12,13,14])
print(type(N))
#by passing lists
N=np.array([1,2,3])
#dimensions in array
n=np.array([23])
print(n.ndim)

<class 'numpy.ndarray'>
1


In [16]:
#string declarationn
str1 = "Hello Welcome to klh university"

str2 = """
    Myself Lalitha
    i am from kl university
    i am studying in 3rd year
    i luv harry potterrrrrrrrrrrrrrrrrrrr

"""
print(str1)
print(str2)

#slicing the stringsss
s = "My name is Lalitha. I am studying in klh"

print(s[11:18])
print(s[:18])
print(s[19:])

#negative indexing

s = "Harry potter is a book adaption"
print(s[4:10])
print(s[-10:-4])


#functions
st = "KONERU LAKSHMAIAH EDUCATIONAL FOUNDATION"

print(st.lower())
print(st.find("I"))
print(st.capitalize())
print(st.swapcase())
print(len(st))


#concatenation of two stirngs
a = "klh"
b = "bowrampet"
c = a+b
print(c)
c = a+" "+b
print(c)


#string formattiong
txt1 = "My name is {fname}. I'm {age}".format(fname="John",age=26)
txt2 = "My name is {0}. I'm {1} ".format("John",26)
txt3 = "My name is {}. I'm {}".format("john",36)
print(txt1)
print(txt2)
print(txt3)

Hello Welcome to klh university

    Myself Lalitha
    i am from kl university
    i am studying in 3rd year
    i luv harry potterrrrrrrrrrrrrrrrrrrr


Lalitha
My name is Lalitha
 I am studying in klh
y pott
k adap
koneru lakshmaiah educational foundation
14
Koneru lakshmaiah educational foundation
koneru lakshmaiah educational foundation
40
klhbowrampet
klh bowrampet
My name is John. I'm 26
My name is John. I'm 26 
My name is john. I'm 36


In [17]:
#while loop
i=1
while i<6:
    print(i)
    i+=1
#while loop with break statement
i=1
while i<6:
    print(i)
    if i==3:
        break
    i+=1
#while loop with continue statement
i=0
while i<6:
    i+=1
    if i==3:
        continue
    print(i)

1
2
3
4
5
1
2
3
1
2
4
5
6


In [18]:
#zeroes array
import numpy as np
P=np.zeros([1])
N=np.zeros([3,4])
print(N)
print(type(N))
#ones array
O=np.ones([2])
N=np.ones([3,4])
print(N)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#array indexing and slicing
import numpy as np
p=np.array([1,2,3,4])
print(p[0])
print(p[3])
q=np.array([[1,2,3,4],[5,6,7,8]])
print(q[0,1])
s=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(s[0,1,2])
#negative indexing
print(p[-1])
print(q[0,-1])
#array slicing
print(p[1:3])
print(p[:3])
print(p[2:])   

1
4
2
6
4
4
[2 3]
[1 2 3]
[3 4]


In [20]:
#print statement
print("Welcome to klh ")

#mathematical operations
b =24
a=30
print(a+b,a-b,a*b,a/b,sep="# ")


''' a = int(input())
b = int(input())

print(a+b,a-b,a*b,a/b,sep="# ")'''

#type print
x=1
y=2.43
z=4+4j

print(type(x))
print(type(y))
print(type(x))

#type casting
s="hlp"
x = int(4.3)
b= float("4.2")
y = str(s)
z = float(5)

Welcome to klh 
54# 6# 720# 1.25
<class 'int'>
<class 'float'>
<class 'int'>


In [21]:
#conditional statements
a=200
b=33
c=67
if(a>b and a>c):
    print("a is greater")
elif(b>a and b>c):
    print("b is greater")
else:
    print("c is greater")

a is greater
